// Manages the bundled slskd daemon: config generation, spawn, health wait, kill.
//
// The desktop app ships slskd binaries under resources/slskd/. On launch we
// write a slskd.yml into the app's private slskd dir (credentials from the
// enhancer's settings, a locally-generated API key) and run slskd on a
// NON-default port (5031) so an existing user-managed slskd on 5030 is never
// disturbed.

import {spawn, type ChildProcess} from 'node:child_process'
import {randomBytes} from 'node:crypto'
import {createWriteStream, existsSync} from 'node:fs'
import {mkdir, readFile, writeFile} from 'node:fs/promises'
import {join} from 'node:path'

export const SLSKD_PORT = 5031

export interface SlskdSetup {
  /** Directory for slskd state (config, db, logs). */
  appDir: string
  /** Where completed downloads land (surfaced to the user). */
  downloadsDir: string
  incompleteDir: string
  username: string
  password: string
}

/** Load (or mint + persist) the local API key the enhancer uses to talk to slskd. */
export async function loadOrCreateApiKey(appDir: string): Promise<string> {
  const keyPath = join(appDir, 'enhancer-api.key')
  try {
    const existing = (await readFile(keyPath, 'utf8')).trim()
    if (existing.length >= 16) return existing
  } catch { /* first run */ }
  const key = randomBytes(24).toString('hex')
  await mkdir(appDir, {recursive: true})
  await writeFile(keyPath, key, {mode: 0o600})
  return key
}

/** Render + write slskd.yml for the bundled daemon. */
export async function writeSlskdConfig(setup: SlskdSetup, apiKey: string): Promise<void> {
  await mkdir(setup.appDir, {recursive: true})
  await mkdir(setup.downloadsDir, {recursive: true})
  await mkdir(setup.incompleteDir, {recursive: true})
  // YAML via template: all interpolated values are locally-generated or
  // user-entered; quoting handles ordinary credentials. (Exotic quotes in a
  // password would need escaping — acceptable for a personal app.)
  const yml = `# Generated by Soulseek Enhancer on every launch — do not edit (changes are overwritten).
soulseek:
  username: "${setup.username}"
  password: "${setup.password}"

web:
  port: ${SLSKD_PORT}
  # HTTPS must be disabled: slskd's HTTPS listener DEFAULTS to port 5031 and
  # would collide with our HTTP port (verified: self "address already in use").
  https:
    disabled: true
  authentication:
    api_keys:
      enhancer:
        key: "${apiKey}"
        role: 'administrator'
        cidr: '127.0.0.0/8,::1/128'

directories:
  downloads: "${setup.downloadsDir}"
  incomplete: "${setup.incompleteDir}"

feature:
  swagger: false
`
  await writeFile(join(setup.appDir, 'slskd.yml'), yml, {mode: 0o600})
}

/** Platform-specific bundled binary path, or null when not packaged (dev mode). */
export function bundledSlskdPath(resourcesPath: string): string | null {
  const name = process.platform === 'win32' ? 'slskd.exe' : 'slskd'
  const candidate = join(resourcesPath, 'slskd', name)
  return existsSync(candidate) ? candidate : null
}

/**
 * Spawn slskd against the generated app dir, teeing its output into
 * `<appDir>/slskd.log` so startup failures are diagnosable. Caller owns the child.
 */
export function spawnSlskd(binaryPath: string, appDir: string): ChildProcess {
  const log = createWriteStream(join(appDir, 'slskd.log'), {flags: 'w'})
  const child = spawn(binaryPath, ['--app-dir', appDir], {
    stdio: ['ignore', 'pipe', 'pipe'],
    detached: false,
  })
  child.stdout?.pipe(log)
  child.stderr?.pipe(log)
  return child
}

/** Poll slskd's health endpoint until it responds or `timeoutMs` elapses. */
export async function waitForSlskd(timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`http://127.0.0.1:${SLSKD_PORT}/health`)
      if (res.ok) return true
    } catch { /* not up yet */ }
    await new Promise((r) => setTimeout(r, 500))
  }
  return false
}

/** Read the Soulseek credentials straight from the enhancer's JSON db file. */
export async function readStoredCredentials(dataDir: string): Promise<{username: string, password: string}> {
  try {
    const raw = await readFile(join(dataDir, 'enhancer-db.json'), 'utf8')
    const parsed = JSON.parse(raw) as {settings?: {soulseek?: {username?: string, password?: string}}}
    return {
      username: parsed.settings?.soulseek?.username ?? '',
      password: parsed.settings?.soulseek?.password ?? '',
    }
  } catch {
    return {username: '', password: ''}
  }
}
